package config

var DefaultVariables = map[string]interface{}{
	"count":                           1000,
	"withSafetyModeUserFields":        true,
	"includePromotedContent":          true,
	"withQuickPromoteEligibility":     true,
	"withVoice":                       true,
	"withV2Timeline":                  true,
	"withDownvotePerspective":         false,
	"withBirdwatchNotes":              true,
	"withCommunity":                   true,
	"withSuperFollowsUserFields":      true,
	"withReactionsMetadata":           false,
	"withReactionsPerspective":        false,
	"withSuperFollowsTweetFields":     true,
	"isMetatagsQuery":                 false,
	"withReplays":                     true,
	"withClientEventToken":            false,
	"withAttachments":                 true,
	"withConversationQueryHighlights": true,
	"withMessageQueryHighlights":      true,
	"withMessages":                    true,
}

var DefaultFeatures = map[string]interface{}{
	"blue_business_profile_image_shape_enabled":                               true,
	"creator_subscriptions_tweet_preview_api_enabled":                         true,
	"freedom_of_speech_not_reach_fetch_enabled":                               false,
	"graphql_is_translatable_rweb_tweet_is_translatable_enabled":              true,
	"graphql_timeline_v2_bookmark_timeline":                                   true,
	"hidden_profile_likes_enabled":                                            true,
	"highlights_tweets_tab_ui_enabled":                                        true,
	"interactive_text_enabled":                                                true,
	"longform_notetweets_consumption_enabled":                                 true,
	"longform_notetweets_inline_media_enabled":                                false,
	"longform_notetweets_rich_text_read_enabled":                              true,
	"longform_notetweets_richtext_consumption_enabled":                        true,
	"profile_foundations_tweet_stats_enabled":                                 true,
	"profile_foundations_tweet_stats_tweet_frequency":                         true,
	"responsive_web_birdwatch_note_limit_enabled":                             true,
	"responsive_web_edit_tweet_api_enabled":                                   true,
	"responsive_web_enhance_cards_enabled":                                    false,
	"responsive_web_graphql_exclude_directive_enabled":                        true,
	"responsive_web_graphql_skip_user_profile_image_extensions_enabled":       false,
	"responsive_web_graphql_timeline_navigation_enabled":                      true,
	"responsive_web_text_conversations_enabled":                               false,
	"responsive_web_twitter_article_data_v2_enabled":                          true,
	"responsive_web_twitter_blue_verified_badge_is_enabled":                   true,
	"rweb_lists_timeline_redesign_enabled":                                    true,
	"spaces_2022_h2_clipping":                                                 true,
	"spaces_2022_h2_spaces_communities":                                       true,
	"standardized_nudges_misinfo":                                             true,
	"subscriptions_verification_info_verified_since_enabled":                  true,
	"tweet_awards_web_tipping_enabled":                                        false,
	"tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled": false,
	"tweetypie_unmention_optimization_enabled":                                true,
	"verified_phone_label_enabled":                                            false,
	"vibe_api_enabled":                                                        true,
	"view_counts_everywhere_api_enabled":                                      true,
}

var AccountOperations = map[string]string{
	"useSendMessageMutation": "MaxK2PKX1F9Z-9SwqwavTw",
	"CreateTweet":            "7TKRKCPuAGsmYde0CudbVg",
	"DeleteTweet":            "VaenaVgh5q5ih7kvyVjgtg",
	"CreateScheduledTweet":   "LCVzRQGxOaGnOnYH01NQXg",
	"DeleteScheduledTweet":   "CTOVqej0JBXAZSwkp1US0g",
	"CreateRetweet":          "ojPdsZsimiJrUGLR1sjUtA",
	"DeleteRetweet":          "iQtK4dl5hBmXewYZuEOKVw",
	"FavoriteTweet":          "lI07N6Otwv1PhnEgXILM7A",
	"UnfavoriteTweet":        "ZYKSe-w7KEslx3JhSIk5LA",
	"CreateBookmark":         "aoDbu3RHznuiSkQ9aNM67Q",
	"DeleteBookmark":         "Wlmlj2-xzyS1GN3a6cj-mQ",
	"CreateList":             "hQAsnViq2BrMLbPuQ9umDA",
	"UpdateList":             "4dCEFWtxEbhnSLcJdJ6PNg",
	"ListsPinMany":           "2X4Vqu6XLneR-XZnGK5MAw",
	"ListPinOne":             "2pYlo-kjdXoNOZJoLzI6KA",
	"ListUnpinOne":           "c4ce-hzx6V4heV5IzdeBkA",
	"ListAddMember":          "P8tyfv2_0HzofrB5f6_ugw",
	"ListRemoveMember":       "DBZowzFN492FFkBPBptCwg",
	"DeleteList":             "UnN9Th1BDbeLjpgjGSpL3Q",
	"EditListBanner":         "Uk0ZwKSMYng56aQdeJD1yw",
	"DeleteListBanner":       "-bOKetDVCMl20qXn7YDXIA",
	"TopicFollow":            "ElqSLWFmsPL4NlZI5e1Grg",
	"TopicUnfollow":          "srwjU6JM_ZKTj_QMfUGNcw",
	"HomeLatestTimeline":     "zhX91JE87mWvfprhYE97xA",
	"HomeTimeline":           "HCosKfLNW1AcOo3la3mMgg",
	"Bookmarks":              "tmd4ifV8RHltzn8ymGg1aw",
}
var FollowSettings = map[string]interface{}{
	"include_profile_interstitial_type": "1",
	"include_blocking":                  "1",
	"include_blocked_by":                "1",
	"include_followed_by":               "1",
	"include_want_retweets":             "1",
	"include_mute_edge":                 "1",
	"include_can_dm":                    "1",
	"include_can_media_tag":             "1",
	"include_ext_has_nft_avatar":        "1",
	"include_ext_is_blue_verified":      "1",
	"include_ext_verified_type":         "1",
	"skip_status":                       "1",
}
